[package]
name = "dsp"
version = "0.2.0"
authors = ["Krzysztof Langner <klangner@gmail.com>"]
description = "Digital Signal Processing"
keywords = ["dsp"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/klangner/dsp"
homepage = "https://github.com/klangner/dsp"
documentation = "https://github.com/klangner/dsp"


[dependencies]
ndarray = "0.7.3"


[dependencies.num-complex]
version = "0.1.32"
default-features = false