[package]
name = "dsp"
version = "0.1.0"
authors = ["Krzysztof Langner <klangner@gmail.com>"]


[dependencies]
ndarray = "0.7.3"


[dependencies.num-complex]
version = "0.1.32"
default-features = false