[package]
name = "tuner"
version = "0.2.0"
authors = ["Krzysztof Langner <klangner@gmail.com>"]
edition = "2018"


[dependencies]
dsp = { path = "../.." }
audrey = "0.2"
gnuplot = "0.0.31"

[dependencies.pitch_calc]
git = "https://github.com/RustAudio/pitch_calc"